Bumped to go 1.20 and added a single assertion
antithesishq/sample-project pull request #2
Opened 2024-01-18 14:23 UTC by herzogp

Includes installing exigen and running it prior to full coverage instrumentation

2024-01-18 14:58 UTC, jdmantithesis requested changes
I don't quite get why were using `go get` in the file? My reading of the recent go documentation is that `go get` just manages the `go.mod` file, which is already done (I think?). Could you walk me through where and how each of the following is supposed to happen:

1. go.mod file is created
2. go.mod file is updated with new dependencies
3. Dependencies are downloaded for building
4. Binary is built using downloaded dependencies

2024-01-18 14:58 UTC, jdmantithesis commented on go/control.go
> +    "github.com/antithesishq/antithesis-sdk-go/assert"
Nit: spacing doesn't align.

2024-01-18 14:58 UTC, jdmantithesis commented on go/control.go
> +    assert.AlwaysTrue("Control program starts", true, nil)
Spacing doesn't align here, either.

2024-01-18 14:58 UTC, jdmantithesis commented on go/Dockerfile.control
> +    go get github.com/golang/glog@v1.2.0 && \
Do we really need to do `go get` on each of these? Looking at the Go documentation, it seems that `go get` is supposed to be for managing the `go.mod` file:

https://go.dev/doc/go-get-install-deprecation

```
In Go 1.18, go get will no longer build packages; it will only be used to add,
update, or remove dependencies in go.mod. Specifically, go get will always
act as if the -d flag were enabled.
```

Also: https://gosamples.dev/update-all-packages/

So if we already have the dependencies in the `go.mod` file which is getting copied into the build container image, why are we using these `go get` commands to further modify that file?

2024-01-18 20:41 UTC, herzogp commented on go/control.go
> +    "github.com/antithesishq/antithesis-sdk-go/assert"
Will line up the spaces - thank you.

The `go.mod` and `go.sum` files represent the manifest for dependencies.  The local module cache includes the actual dependencies, and is updated with `go get`.  I've always found that `go build` does not download dependencies, that job is reserved for: `go get`, `go mod tidy` and `go mod download`. 

`go get` will update the dependencies listed in the `go.mod` file, and pull in any indirect dependencies as well.

I think this will work when a new module is to be introduced:
- Add the package import to the source, and use the package as intended
- `go get` the module
- `go mod tidy`
- `go build`

In the case of 'exigen' it is explicitly downloaded using `go get` prior to attempting to `go install` it.  Trying to `go install` exigen, without previously downloading, did not work.

2024-01-18 20:45 UTC, herzogp commented on go/control.go
> +    assert.AlwaysTrue("Control program starts", true, nil)
Repaired - my editor is configured to expand tabs to spaces, so I'll have to turn this off for go files.

2024-01-18 20:48 UTC, herzogp commented on go/Dockerfile.control
> +    go get github.com/golang/glog@v1.2.0 && \
Because `go get` will actually populate the cache which we get from the bookworm-1.20 image

2024-01-19 15:20 UTC, herzogp commented on go/Dockerfile.control
> +    go get github.com/golang/glog@v1.2.0 && \
Some improvements made here to just explicitly download, install and run exigen

2024-01-22 16:24 UTC, jdmantithesis commented on go/go.sum
> +github.com/antithesishq/antithesis-sdk-go v0.1.9/go.mod h1:qOiIeVdo1mwCsRgb+mOi7CjgU+zKuPNpUiasOEIqUqw=
Why do we have three versions of the Go SDK here?

2024-01-22 16:24 UTC, jdmantithesis commented on go/Dockerfile.control
> +    go get github.com/golang/glog@v1.2.0 && \
If exigen/the Go SDK is in `go.mod`/`go.sum`, won't `go get .` automatically fetch them into the local cache? Or are the dependencies on our SDK/tooling different somehow?

2024-01-24 15:05 UTC, herzogp commented on go/go.sum
> +github.com/antithesishq/antithesis-sdk-go v0.1.9/go.mod h1:qOiIeVdo1mwCsRgb+mOi7CjgU+zKuPNpUiasOEIqUqw=
Cleaned up now.

2024-01-24 17:33 UTC, merged